[MB1]
Name=Clear
Text="<%ClearTXW>"
Color=0
Style=0

[MB2]
Name=CQ
Text="#if StrVARITYPE>>STD || StrVARITYPE==BAUDOT\r\n<%ClearTXW><%TX>CQ CQ CQ de <%MyCall> <%MyCall> <%MyCall> pse K<%RX>\r\n#else\r\n<%ClearTXW><%TX>CQ CQ CQ de <%MyCall> <%MyCall> <%MyCall> pse (<%VARITYPE>) K<%RX>\r\n#endif\r\n"
Color=0
Style=0

[MB3]
Name=CQ2
Text="<%ClearTXW><%TX>CQ CQ CQ de <%MyCall> <%MyCall> <%MyCall>\r\nCQ CQ CQ de <%MyCall> <%MyCall> <%MyCall> pse (<%VARITYPE>) K\r\n<%RX>"
Color=0
Style=0

[MB4]
Name=1x1
Text="<%NETON><%TX><%HisCall> de <%MyCall>\r\n<%RX>"
Color=0
Style=0

[MB5]
Name=2x2
Text="<%NETON><%TX><%IDLE><%IDLE><%HisCall> <%HisCall> de <%MyCall> <%MyCall>\r\n<%RX>"
Color=0
Style=0

[MB6]
Name=RRR
Text="<%IDLE><%IDLE>RRR <%HisCall> de <%MyCall> <%RxCarrier>\r\n#if IsLocal\r\n#if StrVARITYPE == STD/JA\r\n--- <Japanese> ---\r\n#else\r\n--- <%VARITYPE> ---\r\n#endif\r\n#endif\r\n"
Color=0
Style=0

[MB7]
Name=BTU
Text="BTU <%HisCall> de <%MyCall> KN\r\n<%CWID=]><%RX><%AutoClear><%EOF>"
Color=0
Style=0

[MB8]
Name=Test
Text="(1)◎はじめに\r\n(2)  私は日本人なので日本語での会話が好きです。PSK31においても国内局同士\r\n(3)であればできるだけ日本語で会話します。ご存知の通り、PSK31は素晴らしい\r\n(4)伝送方式ですが、日本語を伝送する場合、若干の問題があることが気になって\r\n(5)いました。そして他の東アジア系言語（ハングル、中国語）でも同じ問題を持つと\r\n(6)考えられます。\r\n(7)　このプロジェクトは、この問題を低減する方法について考察し、それを実験する\r\n(8)ことを目的とします。\r\n"
Color=0
Style=0

[MB9]
Name=CH1
Text="<%ShowCH=1,ONOFF>"
Color=0
Style=4

[MB10]
Name=PTT
Text="#if IsPTT\r\n#macro <%PTTOFF>\r\n#else\r\n#macro <%PTTON>\r\n#endif"
Color=0
Style=0

[MB11]
Name=M11
Text="<%SeekPrev>"
Color=0
Style=0

[MB12]
Name=M12
Text="<%SeekNext>"
Color=0
Style=0

[MB13]
Name=CWID
Text="<%TX><%CWID=DE <%MyCall>><%RX><%EOF>"
Color=0
Style=4

[MB14]
Name=TU SK
Text="<%TX><%CWID=TU:><%RX><%EOF>"
Color=0
Style=4

[MB15]
Name=AS
Text="#if !IsTX\r\n<%AutoNET><%AutoReturn><%SkipCR>\r\n#if ValPage!=4\r\n<%Page=4><%SkipCR>\r\n#else\r\n<%Page=3><%SkipCR>\r\n#endif\r\n<%ClearTXW><%SkipCR>\r\n#endif\r\n<%TX><%CWID=@><%RX><%EOF>\r\n"
Color=0
Style=4

[MB16]
Name=1750
Text="<%RxCarrier=_DefaultCarrier>"
Color=0
Style=0

[MB17]
Name=NEST
Text="#define\t_CW\t<%CWID=de <%MyCall>>\r\n<%TX><%RX><%String=_CW><%EOF>"
Color=0
Style=0

[MB18]
Name=FIN
Text="#if IsLocal\r\nRRR <%DearName>有難うございました。 73 SK....<%RX>\r\n#else\r\nRRR Thanks again, <%DearName> CUL, 73 SK....<%RX>\r\n#endif\r\n"
Color=0
Style=0

[MB19]
Name=DemLPF
Text="<%ShowDemLPF>"
Color=0
Style=0

[MB20]
Name=DearName
Text="<%DearName>"
Color=0
Style=0

[MB21]
Name=CH2
Text="<%ShowCH=2,ONOFF>"
Color=0
Style=4

[MB22]
Name=IDLE
Text="<%IDLE><%IDLE>"
Color=0
Style=0

[MB23]
Name=M23
Text=""
Color=0
Style=0

[MB24]
Name=M24
Text="#if !IsDefined(TodayWX) || !StrMacro(<%String=TodayWX>)\r\n#define\tTodayWX\t<%Input=WXを入力>\r\n#endif\r\n#if StrMacro(<%String=TodayWX>)\r\n本日のお天気は、<%String=TodayWX>です。\r\n#endif\r\n"
Color=0
Style=0

[MB25]
Name=REP
Text="#define\tReceiveTime\t5000\r\n#if !IsSQ\r\n<%RepeatTX=ReceiveTime><%ClearTXW><%SkipCR>\r\nCQ CQ CQ de <%MyCall> <%MyCall> <%MyCall> pse (<%VARITYPE>) K\r\n#elseif StrMacro(<%Capture>)\r\n#macro <%HisCall=<%Capture>>\r\n#else\r\n#macro <%Repeat=1000>\r\n#endif\r\n"
Color=0
Style=0

[MB26]
Name=Sound
Text="<%WaterMsg=3,<%SoundName>>"
Color=0
Style=0

[MB27]
Name=CH1,GMSK
Text="<%SetCHMode=1,GMSK>"
Color=0
Style=0

[MB28]
Name=CH1,250
Text="<%SetCHSpeed=1,250.5>"
Color=0
Style=0

[MB29]
Name=MMSSTV
Text="<%Suspend><%Execute=D:\\MMSSTV\\MMSSTV.exe>"
Color=0
Style=0

[MB30]
Name=Tx BPF
Text="<%ShowTxBPF>"
Color=0
Style=0

[MB31]
Name=DECM
Text="<%ShowDECM>"
Color=0
Style=0

[MB32]
Name=SQ=3.0
Text="<%SquelchLevel=3.0>"
Color=0
Style=0

[MB33]
Name=ShowMFSK
Text="<%ShowMFSK>"
Color=0
Style=0

[MB34]
Name=CW
Text="#if StrMacro(<%Input=Input CW text, vvv vvv vvv>)\r\n<%TX><%RX><%CWID=<%Input$>><%EOF>\r\n#endif\r\n"
Color=0
Style=0

[MB35]
Name=M35
Text="#define\tMyRIG\t\tFT1000MP 50W\r\n#define\tMyANT80m\tVertical(7m)\r\n#define\tMyANT40m\tVertical(7m)\r\n#define\tMyANT30m\tMagnetic loop(90cm)\r\n#define\tMyANT20m\tMagnetic loop(90cm)\r\n#define\tMyANT17m\tMagnetic loop(90cm)\r\n#define\tMyANT15m\tMagnetic loop(90cm)\r\n#define\tMyANT12m\tMagnetic loop(90cm)\r\n#define\tMyANT10m\tMagnetic loop(90cm)\r\n#if StrBand==80m\r\n#define\tMyANT\t\tMyANT80m\r\n#elseif StrBand==40m\r\n#define\tMyANT\t\tMyANT40m\r\n#elseif StrBand==30m\r\n#define\tMyANT\t\tMyANT30m\r\n#elseif StrBand==20m\r\n#define\tMyANT\t\tMyANT20m\r\n#elseif StrBand==17m\r\n#define\tMyANT\t\tMyANT17m\r\n#elseif StrBand==15m\r\n#define\tMyANT\t\tMyANT15m\r\n#elseif StrBand==12m\r\n#define\tMyANT\t\tMyANT12m\r\n#else\r\n#define\tMyANT\t\tMyANT10m\r\n#endif\r\n私のリグは<%String=MyRIG>、アンテナは<%String=MyANT>です。\r\n"
Color=0
Style=0

[MB36]
Name=M36
Text="#define\tQTH_HOME\t大阪府高槻市\r\n#define\tQTH_25006\t大阪府三島郡\r\n#define\tQTH_2701\t兵庫県神戸市\r\n#if StrNote >> 25006\r\n#define\tMyQTH\t\tQTH_25006\r\n#elseif StrNote >> 2701\r\n#define\tMyQTH\t\tQTH_2701\r\n#else\r\n#define\tMyQTH\t\tQTH_HOME\r\n#endif\r\n私の現在のQTHは、<%String=MyQTH>です。\r\n"
Color=0
Style=0

[MB37]
Name=Clear
Text="<%ClearTXW>"
Color=0
Style=0

[MB38]
Name=RAND
Text="<%WaterMsg=3,<%RANDOM>>"
Color=0
Style=0

[MB39]
Name=GPS
Text="#define\t_T_NOW\t<%PTIME>\r\n#define\t_T_DIFF\t<%Format=%d,_T_NOW-_T_B4>\r\n#define\t_T_B4\t_T_NOW\r\n<%String=_T_DIFF>\r\n"
Color=0
Style=0

[MB40]
Name=CPU
Text="<%WaterMsg=4,<%CPUBENCHMARK>><%Repeat=1000>"
Color=0
Style=0

[MB41]
Name=TIMEVAL
Text="<%DisableCR>\r\n#define\t_PT\t<%Format=%u,<%PTIME>+9*60*60>\r\n<%WaterMsg=3,<%VALTIME=HOUR,_PT>:<%VALTIME=MINUTE,_PT>:<%VALTIME=SECOND,_PT>>"
Color=0
Style=0

[MB42]
Name=M42
Text="<%VALTIME=LMonth,<%PTIME>>"
Color=0
Style=0

[MB43]
Name=atcppm
Text="<%ATCPPM>\r\n"
Color=0
Style=0

[MB44]
Name=MLEN
Text="<%MStrLen=<%Note>>"
Color=0
Style=0

[MB45]
Name=M45
Text="#define AAA 50"
Color=0
Style=0

[MB46]
Name=M46
Text="<%SeekTop>"
Color=0
Style=0

[MB47]
Name=M47
Text="<%SeekPrev>"
Color=0
Style=0

[MB48]
Name=M48
Text="<%SeekNext>"
Color=0
Style=0

[MB49]
Name=RadioKHz
Text="<%WaterMsg=3,<%RadioKHz>>"
Color=0
Style=0

[MB50]
Name=M50
Text=""
Color=0
Style=0

[MB51]
Name=M51
Text="<%TxIMM=<%CWID=JE3HHT>>"
Color=0
Style=0

[MB52]
Name=M52
Text="#DEFINE\t_DefaultCarrier\t1500\r\n#DEFINE\t_DefaultTEST\t0\r\n"
Color=0
Style=0

[MB53]
Name=M53
Text="#DELETE _DefaultCarrier\r\n#DELETE _DefaultTEST"
Color=0
Style=0

[MB54]
Name=B/2
Text="<%BAUD=<%Format=%f,<%BAUD>/2>>"
Color=0
Style=0

[MB55]
Name=M55
Text=""
Color=0
Style=0

[MB56]
Name=M56
Text=""
Color=0
Style=0

[MB57]
Name=M57
Text=""
Color=0
Style=0

[MB58]
Name=M58
Text=""
Color=0
Style=0

[MB59]
Name=M59
Text=""
Color=0
Style=0

[MB60]
Name=M60
Text="<%MODE=rtty-U>"
Color=0
Style=0

[MB61]
Name=RxFile
Text="<%RxFile=history.txt>"
Color=0
Style=0

[MB62]
Name=RST
Text="<%HisRST>\r\n"
Color=0
Style=0

[MB63]
Name=NR
Text="<%HisNR>"
Color=0
Style=0

[MB64]
Name=Format
Text="<%Format=%g,<%FREQ> % 1>"
Color=0
Style=0

[MB65]
Name=MOD
Text="#define\tVAL\t<%Format=%d,<%FREQ>*1000>\r\n#define\tMOD\t<%Format=%d,VAL % 1000>\r\n<%String=MOD>\r\n"
Color=0
Style=0

[MB66]
Name=Bx2
Text="<%BAUD=<%Format=%f,<%BAUD>*2>>"
Color=0
Style=0

[MB67]
Name=M67
Text="#register\t_MenuSub\t3,6,1\r\n#macro <%DoMenu=_MenuSub>"
Color=0
Style=0

[MB68]
Name=AAA
Text="<%OutputVolume><%Wait=200><%KeyStroke=<%CHAR=I>><%KeyDown=12><%KeyStroke=<%CHAR=P>><%KeyUp=12><%KeyStroke=<%CHAR=R>>"
Color=0
Style=0

[MB69]
Name=DoMenu
Text="#define\tMenuSub\t3,6,1\r\n#macro <%DoMenu=MenuSub>"
Color=0
Style=0

[MB70]
Name=EHistory
Text="<%Execute=notepad.exe ehistory.txt>"
Color=0
Style=0

[MB71]
Name=EMmvari
Text="<%Execute=notepad.exe emmvari.txt>"
Color=0
Style=0

[MB72]
Name=EProject
Text="<%Execute=notepad.exe eproject.txt>"
Color=0
Style=0

[MB73]
Name=Clear
Text="<%ClearTXW>"
Color=0
Style=0

[MB74]
Name=MacTxt
Text="#macro <%MacroText=d:\\Temp\\Macro.txt>"
Color=0
Style=0

[MB75]
Name=M75
Text=""
Color=0
Style=0

[MB76]
Name=M76
Text=""
Color=0
Style=0

[MB77]
Name=0x2 - 2x4
Text="<%DisableCR><%DisableTAB>\r\n#macro <%Menu= 0x2, 0x3, 0x4, -, 1x2, 1x3, 1x4, -, 2x3, 2x4>\r\n#if ValMenu\r\n\t#define\t_His\t<%Format=%c,<%Input$>>\r\n\t#define\t_My\t<%Format=%c,<%Skip$=2,<%Input$>>>\r\n\t<%TX><%RX>\r\n\t#if !Is1stCR\r\n\t\t<%CR>\r\n\t#endif\r\n\t#if IsCall\r\n\t\t<%RepeatText=_His,<%HisCall> >\r\n\t#endif\r\n\tde\r\n\t<%RepeatText=_My, <%MyCall>>\r\n\t pse K<%CR>\r\n#endif"
Color=0
Style=0

[MB78]
Name=M78
Text=""
Color=0
Style=0

[MB79]
Name=M79
Text=""
Color=0
Style=0

[MB80]
Name=M80
Text=""
Color=0
Style=0

[MB81]
Name=M81
Text=""
Color=0
Style=0

[MB82]
Name=M82
Text=""
Color=0
Style=0

[MB83]
Name=M83
Text="<%SeekPrev>"
Color=0
Style=0

[MB84]
Name=M84
Text="<%SeekNext>"
Color=0
Style=0

[MB85]
Name=M85
Text=""
Color=0
Style=0

[MB86]
Name=M86
Text=""
Color=0
Style=0

[MB87]
Name=M87
Text=""
Color=0
Style=0

[MB88]
Name=M88
Text=""
Color=0
Style=0

[MB89]
Name=M89
Text=""
Color=0
Style=0

[MB90]
Name=M90
Text=""
Color=0
Style=0

[MB91]
Name=M91
Text=""
Color=0
Style=0

[MB92]
Name=M92
Text=""
Color=0
Style=0

[MB93]
Name=M93
Text=""
Color=0
Style=0

[MB94]
Name=M94
Text=""
Color=0
Style=0

[MB95]
Name=M95
Text=""
Color=0
Style=0

[MB96]
Name=M96
Text=""
Color=0
Style=0

[MB97]
Name=M97
Text="<%ClearTXW><%TX><%RX>CQ CQ CQ de <%CWID=<%MyCall>><%IDLE><%IDLE><%IDLE> <%MyCall> <%MyCall> <%MyCall> pse k\r\n"
Color=0
Style=0

[MB98]
Name=CQ
Text="<%DisableCR><%ClearTXW><%TX><%RX>\r\n#macro <%Menu=CQ3, CQ4, CQ5>\r\n#if ValMenu\r\n#define\t_cLine\t<%Format=%c,<%Skip$=2,<%Input$>>>\r\n<%RepeatText=_cLine,<%RepeatText=3,CQ >de<%RepeatText=3, <%MyCall>><%CR>>pse k...<%CR>\r\n#endif\r\n<%EOF>\r\n"
Color=0
Style=0

[MB99]
Name=RY
Text="<%RepeatText=3,<%RepeatText=33,RY><%CR>>"
Color=0
Style=0

[MB100]
Name=M100
Text="<%PlayBackButtons=60,30,15>"
Color=0
Style=0

[MB101]
Name=PlayBack
Text="#macro <%MenuB="<%Format=%d,2-<%Cond= IsPlayBack>>",ON,OFF>\r\n#if ValMenu\r\n#macro <%PlayBack=<%Input$>>\r\n#endif"
Color=0
Style=0

[MB102]
Name=Sound
Text="#define\t_tCH\tMONO,LEFT,RIGHT\r\n#define\t_strCH\t<%TableStr=1,<%SoundDevice>>\r\n#define\t_iCH\t<%Table=_strCH,_tCH>\r\n#macro <%MenuB=_iCH,_tCH>\r\n#if ValMenu\r\n#macro <%SoundDevice=<%Input$>><%WaterMsg=3,Sound=<%SoundDevice>>\r\n#endif\r\n"
Color=0
Style=0

[MB103]
Name=M103
Text="<%WaterMsg=3,<%EntityName=<%HisCall>>/<%Continent=<%HisCall>>>"
Color=0
Style=0

[MB104]
Name=ShutDown
Text="<%DisableCR>\r\n#if <%YesNo=Windows will be shut down, are you sure?> == 6\r\n<%ShutDown>\r\n#endif"
Color=0
Style=0

[MB105]
Name=Exit
Text="<%DisableCR>\r\n#if <%YesNo=MMVARIを終了します. ほんまにええですか?> == 6\r\n<%Exit>\r\n#endif"
Color=0
Style=0

[MB106]
Name=DigiOut
Text="<%DisableCR>\r\n#define\t_tLevel\t8192,16384,24576,32768\r\n#define\t_tLabel\tLow, Midium(Default), High, VeryHigh\r\n#define\t_iLevel\t<%Table=<%DigitalLevel>,_tLevel>\r\n#macro <%MenuB=_iLevel,_tLabel>\r\n#if ValMenu\r\n<%DigitalLevel=<%TableStr=<%Menu>,_tLevel>>\r\n#endif"
Color=0
Style=0

[MB107]
Name=M107
Text=""
Color=0
Style=0

[MB108]
Name=ShowClock
Text="<%OnTimer=<%WaterMsg=4,Dem=<%DemodulatorClock>(<%Format=%.2lf,<%DemodulatorClock>*0.5>), FFT=<%FFTClock>/<%FFTSize>>>"
Color=0
Style=0

[MB109]
Name=M109
Text="#if StrVARITYPE>>STD\r\n<%ClearTXW><%TX><%IDLE>CQ CQ CQ<%IDLE><%IDLE> de <%MyCall> <%MyCall> <%MyCall> pse K<%RX>\r\n#else\r\n<%ClearTXW><%TX>CQ CQ CQ de <%MyCall> <%MyCall> <%MyCall> pse (<%VARITYPE>) K<%RX>\r\n#endif\r\n"
Color=0
Style=0

[MB110]
Name=BLK
Text="<%DIDDLE=BLK>"
Color=0
Style=0

[MB111]
Name=LTR
Text="<%DIDDLE=LTR>"
Color=0
Style=0

[MB112]
Name=WaterNoise
Text="#if !IsRepeat\r\n#macro <%Menu=35-65, 30-60, 30-55, 30-50, 10-65>\r\n#if ValMenu == 1\r\n#macro <%WaterNoise=35,65>\r\n#elseif ValMenu == 2\r\n#macro <%WaterNoise=30,60>\r\n#elseif ValMenu == 3\r\n#macro <%WaterNoise=30,55>\r\n#elseif ValMenu == 4\r\n#macro <%WaterNoise=30,50>\r\n#elseif ValMenu == 5\r\n#macro <%WaterNoise=10,65>\r\n#endif\r\n#endif\r\n#macro <%OnTimer=<%WaterMsg=4,<%WaterNoise>dB>>"
Color=0
Style=0

[MB113]
Name=Metric
Text="<%OnTimer=<%WaterMsg=4,Metric=<%MetricMFSK>/<%MetricMFSK=even>/<%MetricMFSK=odd>>>"
Color=0
Style=0

[MB114]
Name=AFCFreq
Text="<%OnTimer=<%WaterMsg=<%AFCFrequency>/<%AFCCount>/<%MetricMFSK>>>"
Color=0
Style=0

[MB115]
Name=DecBench
Text="#macro <%Menu=CPU BENCH, DECM BENCH>\r\n#if ValMenu == 1\r\n#macro <%OnTimer=<%WaterMsg=4,<%CPUBENCHMARK>>>\r\n#elseif ValMenu==2\r\n#macro <%OnTimer=<%WaterMsg=4,<%BENCHDECM>>>\r\n#endif\r\n"
Color=0
Style=0

[MB116]
Name=CQ2
Text="<%ClearTXW><%TX>CQ CQ CQ de <%MyCall> <%MyCall> <%MyCall>\r\nCQ CQ CQ de <%MyCall> <%MyCall> <%MyCall> pse (<%VARITYPE>) K\r\n<%RX>"
Color=0
Style=0

[MB117]
Name=Notch256
Text="<%NotchTaps=128><%WaterMsg=3,<%NotchTaps>>"
Color=0
Style=0

[MB118]
Name=Notch
Text="<%Notch=ONOFF>"
Color=0
Style=0

[MB119]
Name=FileDialog
Text="#if 1\r\n#macro <%FileDialog=, MMV Files(*.mmv)|*.mmv|, Default,mmv, C:\\Sound>\r\n#macro <%WaterMsg=3,<%Input$>>\r\n#if IsFile(<%Input$>)\r\n#macro <%PlaySound=<%Input$>>\r\n#endif\r\n#else\r\n#macro <%PlaySound>\r\n#endif"
Color=0
Style=0

[MB120]
Name=EditEvent
Text="\t#macro <%Menu=OnTimer,OnPTT,OnQSO,OnFind,OnStart,OnExit,OnMode,OnSpeed>\r\n\t#if ValMenu == 1\r\n\t#macro <%OnTimer>\r\n\t#elseif ValMenu == 2\r\n\t#macro <%OnPTT>\t\r\n\t#elseif ValMenu == 3\r\n\t#macro <%OnQSO>\r\n\t#elseif ValMenu == 4\r\n\t#macro <%OnFind>\r\n\t#elseif ValMenu == 5\r\n\t#macro <%OnStart>\r\n\t#elseif ValMenu == 6\r\n\t#macro <%OnExit>\r\n\t#elseif ValMenu == 7\r\n\t#macro <%OnMode>\r\n\t#elseif ValMenu == 8\r\n\t#macro <%OnSpeed>\r\n\t#endif\r\n"
Color=0
Style=0

[MB121]
Name=Capture
Text="#if StrMacro(<%Capture>)\r\n#macro <%HisCall=<%Capture>>\r\n#else\r\n#macro <%Repeat=1000>\r\n#endif"
Color=0
Style=0

[MB122]
Name=UOS_OFF
Text="<%UOS=OFF>"
Color=0
Style=0

[MB123]
Name=UOS_ON
Text="<%UOS=ON>"
Color=0
Style=0

[MB124]
Name=OnTimer
Text="\t#macro <%Menu=AFC, Metric(MFSK), RadioMode, WaterNoise, S/N, UTC, Local, -, Stop>\r\n\t#if ValMenu == 1\r\n\t#macro <%OnTimer=<%WaterMsg=4,<%AFCFrequency>Hz>>\r\n\t#elseif ValMenu == 2\r\n\t#macro <%OnTimer=<%WaterMsg=4,<%MetricMFSK>>>\r\n\t#elseif ValMenu == 3\r\n\t#macro <%OnTimer=<%WaterMsg=4,<%RadioMode>>>\r\n\t#elseif ValMenu == 4\r\n\t#macro <%OnTimer=<%WaterMsg=4,<%WaterNoise>dB>>\r\n\t#elseif ValMenu == 5\r\n\t#macro <%OnTimer=<%WaterMsg=4,S/N=<%AverageLevel>/<%PeakLevel>dB>>\r\n\t#elseif ValMenu == 6\r\n\t#macro <%OnTimer=<%WaterMsg=4,<%UTIME>z>>\r\n\t#elseif ValMenu == 7\r\n\t#macro <%OnTimer=<%WaterMsg=4,<%LTIME>>>\r\n\t#else\r\n\t#macro <%OnTimer=>\r\n\t#endif\r\n"
Color=0
Style=0

[MB125]
Name=WaitC-0
Text="<%RTTYWaitC=0>"
Color=0
Style=0

[MB126]
Name=WaitD-0
Text="<%RTTYWaitD=0>"
Color=0
Style=0

[MB127]
Name=BAUD
Text="<%WaterMsg=3,<%BAUD>>"
Color=0
Style=0

[MB128]
Name=PlayBack
Text="<%PlayBack=10>"
Color=0
Style=0

[MB129]
Name=NotchWidth
Text="<%WaterMsg=3,<%NotchWidth>>"
Color=0
Style=0

[MB130]
Name=200
Text="<%TxShift=200><%RxShift=200>"
Color=0
Style=0

[MB131]
Name=NextMode
Text="<%DisableCR>\r\n#define\t_Table\tGMSK,bpsk,rtty-L\r\n#define\t_Count\t<%Format=%d,<%TableCount=_Table>>\r\n#define\t_CurMode\t<%Format=%d,(_CurMode%_Count)+1>\r\n#macro <%WaterMsg=4,<%String=_CurMode>/<%String=_Count>>\r\n#macro <%WaterMsg=3,<%TableStr=_CurMode,_Table>>\r\n#macro <%MODE=<%TableStr=_CurMode,_Table>>\r\n<%Repeat=3000>"
Color=0
Style=0

[MB132]
Name=SimBaud
Text="#if StrMacro(<%Input=Input ppm>)\r\n#define\t_ppm\t<%Format=%f,<%Input$>*1e-6>\r\n#define\t_baud\t<%Format=%f,<%BAUD> - <%BAUD>*_ppm>\r\n#macro <%SimBAUD=<%Format=%f,_baud>>\r\n#macro <%WaterMsg=3,<%String=_baud>>\r\n#endif"
Color=0
Style=0

[MB133]
Name=M133
Text="RYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRY\r\n"
Color=0
Style=0

[MB134]
Name=Menu
Text="#macro <%Menu=&73 CU SK, &TU SK EE, &SU, &EE>\r\n#if ValMenu==1\r\n<%TX><%RX><%CWID=73CU:><%EOF>\r\n#elseif ValMenu==2\r\n<%TX><%RX><%CWID=TU:EE><%EOF>\r\n#elseif ValMenu==3\r\n<%TX><%RX><%CWID=SU><%EOF>\r\n#elseif ValMenu==4\r\n<%TX><%RX><%CWID=EE><%EOF>\r\n#endif\r\n"
Color=0
Style=0

[MB135]
Name=Final
Text="<%Menu=<%DearName>まいどおおきに..., ほなさいなら..., "TNX AGN <%DearName>, CUL..."><%Input$>"
Color=0
Style=0

[MB136]
Name=Clear
Text="<%ClearTXW>"
Color=0
Style=0

[MB137]
Name=WaitC
Text="<%RTTYWaitC=50>"
Color=0
Style=0

[MB138]
Name=WaitD
Text="<%RTTYWaitD=40>"
Color=0
Style=0

[MB139]
Name=Dupe
Text="<%DupeText>"
Color=0
Style=0

[MB140]
Name=MTTY
Text="#define\t_W\t<%Format="%f",<%BAUD>*0.5>\r\n<%TxShift=_W><%RxShift=_W>\r\n"
Color=0
Style=0

[MB141]
Name=170
Text="<%TxShift=170><%RxShift=170>"
Color=0
Style=0

[MB142]
Name=450
Text="<%TxShift=450><%RxShift=450>"
Color=0
Style=0

[MB143]
Name=DLL
Text="#define\t_CallArg\td:\\test\\MacDLL\\MacDLL.dll, mmmacTest, <%MyCall>\r\n#macro <%WaterMsg=3,<%CallDLL=_CallArg>>"
Color=0
Style=0

[MB144]
Name=Sim.
Text="<%TestSignal>"
Color=0
Style=0

[MB145]
Name=CQ
Text="<%DisableCR><%ClearTXW><%TX><%CODE=7F><%CODE=7F><%CODE=02><%CR>\r\nCQ CQ CQ de NOCALL NOCALL NOCALL<%CR>\r\nCQ CQ CQ de NOCALL NOCALL NOCALL<%CR>\r\nCQ CQ CQ de NOCALL NOCALL NOCALL<%CR>\r\npse K<%CODE=7F><%CODE=7F><%CODE=04>\r\n<%RX>"
Color=0
Style=0

[MB146]
Name=FreqMenu
Text="#if !IsDefined(_Rig)\r\n#define\t_Rig\tCI-V\r\n#endif\r\n\t#macro <%Menu=7028.5,10141.5,14072.5,18102.5,21072.5,28072.5,50980.0,144450.0>\r\n\t#if ValMenu\r\n\t#if IsRadioLSB\r\n\t#macro <%RadioKHz=_Rig,<%Input$>+<%RxCarrier>*0.001>\r\n\t#else\r\n\t#macro <%RadioKHz=_Rig,<%Input$>-<%RxCarrier>*0.001>\r\n\t#endif\r\n\t#endif\r\n"
Color=0
Style=0

[MB147]
Name=MODE
Text="#define\t_Rig\tCI-V\r\n#define\t_t_Mode\tLSB,USB,CW,AM,FM,RTTY,PACKET\r\n#macro <%MenuB="<%Table=<%RadioMode>,_t_Mode>",_t_Mode>\r\n#if ValMenu\r\n#macro <%RadioMode=_Rig,<%Input$>>\r\n#endif\r\n"
Color=0
Style=0

[MB148]
Name=+500
Text="#define\t_FQ\t7.028\r\n#define\t_Rig\tCI-V\r\n#if <%RadioKHz>\r\n#macro <%RadioKHz=_Rig,<%RadioKHz>+0.5>\r\n#else\r\n#macro <%RadioKHz=_Rig,_FQ*1000>\r\n#endif"
Color=0
Style=0

[MB149]
Name=-500
Text="#define\t_FQ\t7.028\r\n#define\t_Rig\tCI-V\r\n#if <%RadioKHz>\r\n#macro <%RadioKHz=_Rig,<%RadioKHz>-0.5>\r\n#else\r\n#macro <%RadioKHz=_Rig,_FQ*1000>\r\n#endif"
Color=0
Style=0

[MB150]
Name=SetTone
Text="#define\t_Tone\t1750\r\n#define\t_Rig\tCI-V\r\n#macro <%Menu=1000,1200,1500,1750,2000>\r\n#if ValMenu\r\n#define\t_Tone\t<%Input$>\r\n#define\t_OffKHz\t<%Format=%f,(<%RxCarrier>-_Tone)*0.001>\r\n#if IsRadioLSB\r\n#macro <%RadioKHz=_Rig,<%RadioKHz>-_OffKHz>\r\n#else\r\n#macro <%RadioKHz=_Rig,<%RadioKHz>+_OffKHz>\r\n#endif\r\n#macro <%RxCarrier=_Tone>\r\n#endif"
Color=0
Style=0

[MB151]
Name=RigQuery?
Text="#if IsRadioLSB\r\n#macro <%WaterMsg=3,<%RadioKHz> <%RadioMode> IsRadioLSB=TRUE>\r\n#else\r\n#macro <%WaterMsg=3,<%RadioKHz> <%RadioMode> IsRadioLSB=FALSE>\r\n#endif\r\n"
Color=0
Style=0

[MB152]
Name=M152
Text=""
Color=0
Style=0

[MB153]
Name=M153
Text=""
Color=0
Style=0

[MB154]
Name=M154
Text=""
Color=0
Style=0

[MB155]
Name=M155
Text=""
Color=0
Style=0

[MB156]
Name=M156
Text=""
Color=0
Style=0

[MB157]
Name=M157
Text=""
Color=0
Style=0

[MB158]
Name=M158
Text=""
Color=0
Style=0

[MB159]
Name=M159
Text=""
Color=0
Style=0

[MB160]
Name=M160
Text=""
Color=0
Style=0

